//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace DISUnity.DataType.Enums.SISO_REF_010.SISO_REF_010_2011_1_RC2
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( AnonymousType=true, Namespace="http://svn.ebvdoc.org/trunk" )]
    [System.Xml.Serialization.XmlRootAttribute( Namespace="http://svn.ebvdoc.org/trunk", IsNullable=false )]
    public partial class ebv
    {

        private revisions_t revisionsField;

        private generictable_t[] itemsField;

        private string titleField;

        private string releaseField;

        private string hrefField;

        private System.DateTime dateField;

        private string descriptionField;

        private string organisationField;

        /// <remarks/>
        public revisions_t revisions
        {
            get
            {
                return this.revisionsField;
            }
            set
            {
                this.revisionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "bitmask", typeof( bitmask_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "cet", typeof( cet_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "cot", typeof( cot_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "dict", typeof( dict_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "enum", typeof( enum_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "record", typeof( record_t ) )]
        public generictable_t[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string release
        {
            get
            {
                return this.releaseField;
            }
            set
            {
                this.releaseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="date" )]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string organisation
        {
            get
            {
                return this.organisationField;
            }
            set
            {
                this.organisationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class revisions_t : generictable_t
    {

        private revision_t[] revisionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "revision" )]
        public revision_t[] revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class revision_t
    {

        private object[] itemsField;

        private string titleField;

        private System.DateTime dateField;

        private bool dateFieldSpecified;

        private string uuidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "cr", typeof( cr_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "cr_range", typeof( cr_range_t ) )]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="date" )]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class cr_t
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="positiveInteger" )]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class datatype_t
    {

        private string nameField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class field_t
    {

        private datatype_t[] datatypeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "datatype" )]
        public datatype_t[] datatype
        {
            get
            {
                return this.datatypeField;
            }
            set
            {
                this.datatypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class col_t
    {

        private string keyField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class meta_t
    {

        private string keyField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( object_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( entity_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( genericentrydescription_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( genericentryrange_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( subcategory_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( specific_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( extra_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( category_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( bitmaskrow_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( enumrow_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( genericentrysingle_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( category_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( extra_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( specific_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( subcategory_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( bitmaskrow_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( enumrow_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( genericentrystring_t ) )]
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public abstract partial class genericentry_t
    {

        private object[] itemsField;

        private string footnoteField;

        private string xrefField;

        private bool deprecatedField;

        private bool deprecatedFieldSpecified;

        private genericentry_tStatus statusField;

        private bool statusFieldSpecified;

        private bool draft1278Field;

        private bool draft1278FieldSpecified;

        private string uuidField;

        private string baseuuidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "cr", typeof( cr_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "cr_range", typeof( cr_range_t ) )]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string footnote
        {
            get
            {
                return this.footnoteField;
            }
            set
            {
                this.footnoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="positiveInteger" )]
        public string xref
        {
            get
            {
                return this.xrefField;
            }
            set
            {
                this.xrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deprecated
        {
            get
            {
                return this.deprecatedField;
            }
            set
            {
                this.deprecatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deprecatedSpecified
        {
            get
            {
                return this.deprecatedFieldSpecified;
            }
            set
            {
                this.deprecatedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public genericentry_tStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool draft1278
        {
            get
            {
                return this.draft1278Field;
            }
            set
            {
                this.draft1278Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool draft1278Specified
        {
            get
            {
                return this.draft1278FieldSpecified;
            }
            set
            {
                this.draft1278FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string baseuuid
        {
            get
            {
                return this.baseuuidField;
            }
            set
            {
                this.baseuuidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class cr_range_t
    {

        private int value_minField;

        private int value_maxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value_min
        {
            get
            {
                return this.value_minField;
            }
            set
            {
                this.value_minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value_max
        {
            get
            {
                return this.value_maxField;
            }
            set
            {
                this.value_maxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute( AnonymousType=true, Namespace="http://svn.ebvdoc.org/trunk" )]
    public enum genericentry_tStatus
    {

        /// <remarks/>
        pending,

        /// <remarks/>
        @new,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class object_t : genericentry_t
    {

        private genericentrydescription_t[] items1Field;

        private string domainField;

        private string kindField;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "category", typeof( category_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "category_range", typeof( category_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string kind
        {
            get
            {
                return this.kindField;
            }
            set
            {
                this.kindField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class category_t : genericentrysingle_t
    {

        private genericentrydescription_t[] items1Field;

        private bool transferredField;

        private bool transferredFieldSpecified;

        private bool variationField;

        private bool variationFieldSpecified;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "subcategory", typeof( subcategory_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "subcategory_range", typeof( subcategory_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred
        {
            get
            {
                return this.transferredField;
            }
            set
            {
                this.transferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified
        {
            get
            {
                return this.transferredFieldSpecified;
            }
            set
            {
                this.transferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation
        {
            get
            {
                return this.variationField;
            }
            set
            {
                this.variationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified
        {
            get
            {
                return this.variationFieldSpecified;
            }
            set
            {
                this.variationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class subcategory_t : genericentrysingle_t
    {

        private genericentrydescription_t[] items1Field;

        private bool transferredField;

        private bool transferredFieldSpecified;

        private bool variationField;

        private bool variationFieldSpecified;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "specific", typeof( specific_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "specific_range", typeof( specific_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred
        {
            get
            {
                return this.transferredField;
            }
            set
            {
                this.transferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified
        {
            get
            {
                return this.transferredFieldSpecified;
            }
            set
            {
                this.transferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation
        {
            get
            {
                return this.variationField;
            }
            set
            {
                this.variationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified
        {
            get
            {
                return this.variationFieldSpecified;
            }
            set
            {
                this.variationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class specific_t : genericentrysingle_t
    {

        private genericentrydescription_t[] items1Field;

        private bool transferredField;

        private bool transferredFieldSpecified;

        private bool variationField;

        private bool variationFieldSpecified;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "extra", typeof( extra_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "extra_range", typeof( extra_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred
        {
            get
            {
                return this.transferredField;
            }
            set
            {
                this.transferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified
        {
            get
            {
                return this.transferredFieldSpecified;
            }
            set
            {
                this.transferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation
        {
            get
            {
                return this.variationField;
            }
            set
            {
                this.variationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified
        {
            get
            {
                return this.variationFieldSpecified;
            }
            set
            {
                this.variationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class extra_t : genericentrysingle_t
    {

        private bool transferredField;

        private bool transferredFieldSpecified;

        private bool variationField;

        private bool variationFieldSpecified;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred
        {
            get
            {
                return this.transferredField;
            }
            set
            {
                this.transferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified
        {
            get
            {
                return this.transferredFieldSpecified;
            }
            set
            {
                this.transferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation
        {
            get
            {
                return this.variationField;
            }
            set
            {
                this.variationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified
        {
            get
            {
                return this.variationFieldSpecified;
            }
            set
            {
                this.variationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( category_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( extra_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( specific_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( subcategory_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( bitmaskrow_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( enumrow_t ) )]
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public abstract partial class genericentrysingle_t : genericentrydescription_t
    {

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( genericentryrange_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( subcategory_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( specific_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( extra_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( category_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( bitmaskrow_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( enumrow_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( genericentrysingle_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( category_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( extra_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( specific_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( subcategory_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( bitmaskrow_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( enumrow_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( genericentrystring_t ) )]
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public abstract partial class genericentrydescription_t : genericentry_t
    {

        private string descriptionField;

        private int groupField;

        private bool groupFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupSpecified
        {
            get
            {
                return this.groupFieldSpecified;
            }
            set
            {
                this.groupFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( subcategory_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( specific_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( extra_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( category_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( bitmaskrow_range_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( enumrow_range_t ) )]
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public abstract partial class genericentryrange_t : genericentrydescription_t
    {

        private int value_minField;

        private int value_maxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value_min
        {
            get
            {
                return this.value_minField;
            }
            set
            {
                this.value_minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value_max
        {
            get
            {
                return this.value_maxField;
            }
            set
            {
                this.value_maxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class subcategory_range_t : genericentryrange_t
    {

        private genericentrydescription_t[] items1Field;

        private bool transferredField;

        private bool transferredFieldSpecified;

        private bool variationField;

        private bool variationFieldSpecified;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "specific", typeof( specific_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "specific_range", typeof( specific_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred
        {
            get
            {
                return this.transferredField;
            }
            set
            {
                this.transferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified
        {
            get
            {
                return this.transferredFieldSpecified;
            }
            set
            {
                this.transferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation
        {
            get
            {
                return this.variationField;
            }
            set
            {
                this.variationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified
        {
            get
            {
                return this.variationFieldSpecified;
            }
            set
            {
                this.variationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class specific_range_t : genericentryrange_t
    {

        private genericentrydescription_t[] items1Field;

        private bool transferredField;

        private bool transferredFieldSpecified;

        private bool variationField;

        private bool variationFieldSpecified;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "extra", typeof( extra_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "extra_range", typeof( extra_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred
        {
            get
            {
                return this.transferredField;
            }
            set
            {
                this.transferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified
        {
            get
            {
                return this.transferredFieldSpecified;
            }
            set
            {
                this.transferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation
        {
            get
            {
                return this.variationField;
            }
            set
            {
                this.variationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified
        {
            get
            {
                return this.variationFieldSpecified;
            }
            set
            {
                this.variationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class extra_range_t : genericentryrange_t
    {

        private bool transferredField;

        private bool transferredFieldSpecified;

        private bool variationField;

        private bool variationFieldSpecified;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred
        {
            get
            {
                return this.transferredField;
            }
            set
            {
                this.transferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified
        {
            get
            {
                return this.transferredFieldSpecified;
            }
            set
            {
                this.transferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation
        {
            get
            {
                return this.variationField;
            }
            set
            {
                this.variationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified
        {
            get
            {
                return this.variationFieldSpecified;
            }
            set
            {
                this.variationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class category_range_t : genericentryrange_t
    {

        private genericentrydescription_t[] items1Field;

        private bool transferredField;

        private bool transferredFieldSpecified;

        private bool variationField;

        private bool variationFieldSpecified;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "subcategory", typeof( subcategory_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "subcategory_range", typeof( subcategory_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred
        {
            get
            {
                return this.transferredField;
            }
            set
            {
                this.transferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified
        {
            get
            {
                return this.transferredFieldSpecified;
            }
            set
            {
                this.transferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation
        {
            get
            {
                return this.variationField;
            }
            set
            {
                this.variationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified
        {
            get
            {
                return this.variationFieldSpecified;
            }
            set
            {
                this.variationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class bitmaskrow_range_t : genericentryrange_t
    {

        private genericentrydescription_t[] items1Field;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "enumrow", typeof( enumrow_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "enumrow_range", typeof( enumrow_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class enumrow_t : genericentrysingle_t
    {

        private meta_t[] metaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "meta" )]
        public meta_t[] meta
        {
            get
            {
                return this.metaField;
            }
            set
            {
                this.metaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class enumrow_range_t : genericentryrange_t
    {

        private meta_t[] metaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "meta" )]
        public meta_t[] meta
        {
            get
            {
                return this.metaField;
            }
            set
            {
                this.metaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class genericentrystring_t : genericentrydescription_t
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class bitmaskrow_t : genericentrysingle_t
    {

        private genericentrydescription_t[] items1Field;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "enumrow", typeof( enumrow_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "enumrow_range", typeof( enumrow_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class entity_t : genericentry_t
    {

        private genericentrydescription_t[] items1Field;

        private string kindField;

        private string domainField;

        private string countryField;

        private string uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "category", typeof( category_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "category_range", typeof( category_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string kind
        {
            get
            {
                return this.kindField;
            }
            set
            {
                this.kindField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="nonNegativeInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( record_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( cot_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( cet_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( bitmask_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( enum_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( dict_t ) )]
    [System.Xml.Serialization.XmlIncludeAttribute( typeof( revisions_t ) )]
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public abstract partial class generictable_t
    {

        private object[] itemsField;

        private string uidField;

        private string nameField;

        private bool draft1278Field;

        private bool draft1278FieldSpecified;

        private bool deprecatedField;

        private bool deprecatedFieldSpecified;

        private int groupField;

        private bool groupFieldSpecified;

        private string footnoteField;

        private string applicabilityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "cr", typeof( cr_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "cr_range", typeof( cr_range_t ) )]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType="positiveInteger" )]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool draft1278
        {
            get
            {
                return this.draft1278Field;
            }
            set
            {
                this.draft1278Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool draft1278Specified
        {
            get
            {
                return this.draft1278FieldSpecified;
            }
            set
            {
                this.draft1278FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deprecated
        {
            get
            {
                return this.deprecatedField;
            }
            set
            {
                this.deprecatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deprecatedSpecified
        {
            get
            {
                return this.deprecatedFieldSpecified;
            }
            set
            {
                this.deprecatedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupSpecified
        {
            get
            {
                return this.groupFieldSpecified;
            }
            set
            {
                this.groupFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string footnote
        {
            get
            {
                return this.footnoteField;
            }
            set
            {
                this.footnoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string applicability
        {
            get
            {
                return this.applicabilityField;
            }
            set
            {
                this.applicabilityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class record_t : generictable_t
    {

        private field_t[] fieldField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "field" )]
        public field_t[] field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class cot_t : generictable_t
    {

        private object_t[] objectField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "object" )]
        public object_t[] @object
        {
            get
            {
                return this.objectField;
            }
            set
            {
                this.objectField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class cet_t : generictable_t
    {

        private entity_t[] entityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "entity" )]
        public entity_t[] entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class bitmask_t : generictable_t
    {

        private genericentrydescription_t[] items1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "bitmaskrow", typeof( bitmaskrow_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "bitmaskrow_range", typeof( bitmaskrow_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class enum_t : generictable_t
    {

        private col_t[] headerField;

        private genericentrydescription_t[] items1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute( "col", typeof( col_t ), IsNullable=false )]
        public col_t[] header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "enumrow", typeof( enumrow_t ) )]
        [System.Xml.Serialization.XmlElementAttribute( "enumrow_range", typeof( enumrow_range_t ) )]
        public genericentrydescription_t[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.3038" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace="http://svn.ebvdoc.org/trunk" )]
    public partial class dict_t : generictable_t
    {

        private genericentrystring_t[] dictrowField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "dictrow" )]
        public genericentrystring_t[] dictrow
        {
            get
            {
                return this.dictrowField;
            }
            set
            {
                this.dictrowField = value;
            }
        }
    }
}