
namespace DISUnity.DataType.Enums
{
    /// <summary>
    /// Tactical data link type.
    /// </summary>
    public enum TacticalDataLinkType 
    {
        Other                                                             = 0,
        PADIL                                                             = 1,
        NATOLink_1                                                        = 2,
        ATDL_1                                                            = 3,
        Link11B_TADILB                                                    = 4,
        SituationalAwarenessDataLink_SADL                                 = 5,
        Link16LegacyFormat_JTIDS_TADIL_J                                  = 6,
        Link16LegacyFormat_JTIDS_FDL_TADIL_J                              = 7,
        Link11A_TADILA                                                    = 8,
        IJMS                                                              = 9,
        Link4A_TADILC                                                     = 10,
        Link4C                                                            = 11,
        TIBS                                                              = 12,
        ATL                                                               = 13,
        ConstantSource                                                    = 14,
        AbbreviatedCommandandControl                                      = 15,
        MILSTAR                                                           = 16,
        ATHS                                                              = 17,
        OTHGOLD                                                           = 18,
        TACELINT                                                          = 19,
        WeaponsDataLink_AWW_13                                            = 20,
        AbbreviatedCommandandControl1                                     = 21,
        EnhancedPositionLocationReportingSystem_EPLRS                     = 22,
        PositionLocationReportingSystem_PLRS                              = 23,
        SINCGARS                                                          = 24,
        HaveQuickI                                                        = 25,
        HaveQuickII                                                       = 26,
        HaveQuickIIASaturn                                                = 27,
        Intra_FlightDataLink1                                             = 28,
        Intra_FlightDataLink2                                             = 29,
        ImprovedDataModem_IDM                                             = 30,
        AirForceApplicationProgramDevelopment_AFAPD                       = 31,
        CooperativeEngagementCapability_CEC                               = 32,
        ForwardAreaAirDefense_FAAD_DataLink_FDL                           = 33,
        GroundBasedDataLink_GBDL                                          = 34,
        IntraVehicularInfoSystem_IVIS                                     = 35,
        MarineTacticalSystem_MTS                                          = 36,
        TacticalFireDirectionSystem_TACFIRE                               = 37,
        IntegratedBroadcastService_IBS                                    = 38,
        AirborneInformationTransfer_ABIT                                  = 39,
        AdvancedTacticalAirborneReconnaissanceSystem_ATARS_DataLink       = 40,
        BattleGroupPassiveHorizonExtensionSystem_BGPHES_DataLink          = 41,
        CommonHighBandwidthDataLink_CHBDL                                 = 42,
        GuardrailInteroperableDataLink_IDL                                = 43,
        GuardrailCommonSensorSystemOne_CSS1_DataLink                      = 44,
        GuardrailCommonSensorSystemTwo_CSS2_DataLink                      = 45,
        GuardrailCSS2Multi_RoleDataLink_MRDL                              = 46,
        GuardrailCSS2DirectAirtoSatelliteRelay_DASR_DataLink              = 47,
        LineofSight_LOS_DataLinkImplementation_LOStether                  = 48,
        LightweightCDL_LWCDL                                              = 49,
        L_52M_SR_71                                                       = 50,
        RivetReach_RivetOwlDataLink                                       = 51,
        SeniorSpan                                                        = 52,
        SeniorSpur                                                        = 53,
        SeniorStretch                                                     = 54,
        SeniorYearInteroperableDataLink_IDL                               = 55,
        SpaceCDL                                                          = 56,
        TR_1modeMISTAirborneDataLink                                      = 57,
        Ku_bandSATCOMDataLinkImplementation_UAV                           = 58,
        MissionEquipmentControlDatalink_MECDL                             = 59,
        RadarDataTransmittingSetDataLink                                  = 60,
        SurveillanceandControlDataLink_SCDL                               = 61,
        TacticalUAVVideo                                                  = 62,
        UHFSATCOMDataLinkImplementation_UAV                               = 63,
        TacticalCommonDataLink_TCDL                                       = 64,
        LowLevelAirPictureInterface_LLAPI                                 = 65,
        WeaponsDataLink_AGM_130                                           = 66,
        GC3                                                               = 99,
        Link16StandardizedFormat_JTIDS_MIDS_TADILJ                        = 100,
        Link16EnhancedDataRate_EDRJTIDS_MIDS_TADIL_J                      = 101,
        JTIDS_MIDSNetDataLoad_TIMS_TOMS                                   = 102,
        Link22                                                            = 103,
        AFIWCIADSCommunicationsLinks                                      = 104
    }
}
